### ISSUE TITLE
Pigeon Delivery

### ISSUE THREAD

**Issue by SebSemos** [aqariio/Fowl-Play#17]
So. I hate to be that guy, but I'm opening an issue without having all the infos lol
So I tried to use the pigeon mecanic but nothing happened. I play on 1.20.1 still and I don't know how I got acces to bundles, but I got them. 
F3+H show minecraft:bundle for them but must be a mod that enable them 🤷‍♂️ I'll do some check to see wivh one as soon I got time

I also have a very poor internet connection, the issue simply could very be that (I have tested with my two accounts on my server) but like, my connection is so bad I get connection timeout when using both. During my testing it held just for a good 10 minutes but the pigeon didn't deliver anything...
I also didn't switch my server to latest version for testing. Uploading a backup of my world would takes about 12 hours. Forgive my laziness 😅

PS, the pigeon takes the bundle.

**Comment by aqariio** [comment]
Honestly, I wouldn't be surprised if the pigeon bundle delivering doesn't work, because I haven't had a chance to test it ever since I updated the ai for all the birds. I'll take a look at it and see what the issue is. The fix will probably come with the next update.

Probably not an issue on your end, so no need to worry! (btw I think there's an experimental toggle that enables bundles, not sure if that's what you used)

**Comment by aqariio** [comment]
I forgot to mention that there is a maximum distance for the pigeon, that being 1024 blocks. I'll remove this in the next update, but that could be a reason why it wasn't working. (I haven't tested multiplayer yet, just looking at the code)

**Comment by aqariio** [comment]
After some testing it appears that the pigeon does teleport to the recipient. However, a bug that is present in the base game makes the mob invisible. Relogging appears to fix this. 

This is caused by [MC-273361](https://bugs.mojang.com/browse/MC-273361), which turns entities teleporting from force loaded chunks invisible.

Unfortunately, I can't fix this without updating the mod to a later version of the game.
