### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by GitCodMaster** [aqariio/Fowl-Play#18]
i dont know why its crashing, if i take fowl play out of the mods list, it isn't crashing anymore.

[latest.log](https://github.com/user-attachments/files/17834388/latest.log)

**Comment by aqariio** [comment]
Is that the full crash log? I don't see any error messages. I'm not familiar with Forge, so if that is indeed the full log then I don't really know what the cause might be. It doesn't provide any useful information, not even about whether my mod is involved in the crash.

**Comment by GitCodMaster** [comment]
the new beta version somehow make it worse. i now get a blue screen from windows if i start the game with the mod on 80% chance. here is the full crash log when it doesnt crash my whole pc
[2024-11-23-7.log.gz](https://github.com/user-attachments/files/17882236/2024-11-23-7.log.gz)
[debug.log](https://github.com/user-attachments/files/17882237/debug.log)
[latest.log](https://github.com/user-attachments/files/17882238/latest.log)
[debug-1.log.gz](https://github.com/user-attachments/files/17882239/debug-1.log.gz)

**Comment by aqariio** [comment]
Are you using the Sinytra connector compatible version of my mod? If not, you can find it here:
https://github.com/aqariio/Fowl-Play/releases/tag/v1.0.0-beta.1%2Bsinytra

Honestly, I still don't have a very good idea of what the problem is. Because of your extensive mod list, it could be an incompatibility with any one of those mods, and there wouldn't really be a way of figuring out which one it is quickly. Although, it seems that there are a lot of error messages coming from Essential, maybe that might be the problem?

**Comment by GitCodMaster** [comment]
oh thanks. it now works with the sinytra version, thanks for the tipp i removed essential mod since it also doesnt load. but now there is another problem. i cant swim or moove in water at all, if i enable the mod. im 100% shure that its caused by Fowl-Play, cuz if i delete the mod or disable it, i can swim again

**Comment by aqariio** [comment]
Oh right, I forgot. #15 has the answer to this question. I should probably make an FAQ so that people using Sinytra connector don't encounter this problem.

**Comment by GitCodMaster** [comment]
And you probably also should put a big warning in the mod description for the sinytra connector version. if not done already.
