### ISSUE TITLE
[Request] Decrease distance from which birds can be heard

### ISSUE THREAD

**Issue by xXNickznXx** [aqariio/Fowl-Play#21]
Based on the description from the [fabric docs](https://docs.fabricmc.net/develop/sounds/using-sounds#volume-and-pitch), some birds can be heard up to 192 blocks away. For comparison, a cow can only be heard 16 blocks away.

This makes the bird sounds more than annoying, as you can literally hear every bird within that distance.

My request is to reduce the distance to a "vanilla" level, or even better, to make it configurable.

**Comment by aqariio** [comment]
This is intended behavior. Bird songs and calls are usually louder and can be heard from further away when compared to a cow mooing. 

The purpose of this is to allow players to hear a wide range of bird vocalizations, especially within biomes like forests. If the attenuation distance is reduced to 16 blocks, you would barely hear anything, and forests would feel much less alive.

I will consider adding configuration for calls and sounds, as there is no easy way to customize them otherwise.

**Comment by xXNickznXx** [comment]
I understand the intention. For me its just a strain on the ears to hear 20+ birds at the same time.

Thanks for considering the configuration.

And other than that I love the mod, so keep it up. :)

**Comment by aqariio** [comment]
Glad you're enjoying the mod! The sound attenuation config will be added in the next update, I hope that will help.
