### ISSUE TITLE
Spawn and Sound control

### ISSUE THREAD

**Issue by Disketaa** [aqariio/Fowl-Play#8]
I'm trying to place this mod in my skyblock-themed modpack but there is no configuration to set some things up. Like I'd like to change how frequently birds spawn and volume of ambient sound of birds. 

Maybe some configuration:

- Bird spawn rate
- Bird min group size (to spawn birds less frequently but with more quantity) like a flock
- Bird ambient sound volume
- Bird ambient sound rareness

Greet to see how the mod is going on! I really like to add some ambience in my world with tangible sources of these sounds, not just an other "Ambience" mods with ton of sounds out of nowhere. I remember crocodile sounds from Dynamic Surroundings xd but there are no crocodiles in the game

**Comment by aqariio** [comment]
Hello! Thanks for leaving an issue, and I'm glad you enjoy my mod!

I'll definitely try to make the mod more configurable, either through making some features data-driven or through configs. I'll be sure to include spawn weight, group sizes, and ambient sound customization. If you have any other suggestions for possible configurations, just let me know!

These features will probably come with the next update. However, it might take some time (1-2 weeks) before the update is ready, so if you need these configuration options sooner, I can release a quick patch that includes these options.

**Comment by Disketaa** [comment]
Yay. Take your time, no pressure at all. 😉

**Comment by aqariio** [comment]
I've implemented a config for spawning, like spawn weight and group sizes. However, I am rather reluctant to add configuration for bird calls, because at that point the config would feel bloated. 
First, there already exist mods that add control for individual sounds. 
Second, their calls are intended as an extension of their behaviours, and in the future might even be altered further to have special calls for different situations. As a result, I'm not sure if making it configurable is the best approach.
Let me know what you think about this!

**Comment by Disketaa** [comment]
Oki. I hope I can change sound volume through sounds.json file, so that would not be a problem. Thanks for the spawn control implementation tho =)

**Comment by aqariio** [comment]
To my knowledge, sounds.json only defines which sound files are played by a specific sound event. I've found this mod which allows you to customize individual sounds: 
https://modrinth.com/mod/sound-controller

**Comment by Disketaa** [comment]
sounds.json supports volume and pitch parameters, so it might be possible to change the volume via resourcepack 

```
...{
  "music.game": {
    "replace": true,
    "sounds": [
      {
        "name": "music/game/keys-of-moon_after-the-rain",
        "volume": 0.1,
        "stream": true
      },...
```

**Comment by Disketaa** [comment]
By the way, I hear bird sounds from a longest distance that other mobs, is it right? 
If so, sometimes it can be odd to catch bird sound from a distant but louder then other mobs than closer to you. I mean sometimes bird call sounds like it was played directly in your head rather then far away. I don't know how to describe that feeling correctly.

**Comment by aqariio** [comment]
> sounds.json supports volume and pitch parameters, so it might be possible to change the volume via resourcepack

Oh, that's very interesting! I didn't know that. I'll try it out.

Bird sounds do indeed have a longer range than sounds from other mobs. If any of the sounds feel very close, it might be because I forgot to set the channel to mono, which is what allows for directionality and attenuation. I'll check the sounds again to verify that they are all mono.
